FROM postgres:alpine

# Environment variables
ENV POSTGRES_PASSWORD=melody
ENV POSTGRES_USER=mehdi
ENV POSTGRES_DB=ft_transcendence_database

RUN apk update && apk add --no-cache bash

# Expose PostgreSQL port
EXPOSE 5432