# Generated by Django 3.2.25 on 2024-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20240709_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='transaction_hashes',
            field=models.JSONField(default=list),
        ),
    ]
