# Generated by Django 3.2.25 on 2024-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_tournament_transaction_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='transaction_hashes',
            field=models.JSONField(default=list),
        ),
    ]
