version: '3.8'

services:
  ganache:
    container_name: container_ganache
    build:
      context: ganache/
      dockerfile: Dockerfile
    volumes:
      - ganache-data:/ganache/data
    networks:
      - ft_transcendence_network

  ft_transcendence_database:
    image: ft_transcendence/database
    env_file : .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    container_name: ft_transcendence_database
    build:
      context: database/
      dockerfile: Dockerfile
    networks:
      - ft_transcendence_network
    volumes:
      - ft_transcendence_database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    image: ft_transcendence/backend
    container_name: ft_transcendence_backend
    env_file : .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_ADMIN_USER: ${DJANGO_ADMIN_USER}
      DJANGO_ADMIN_PASSWORD: ${DJANGO_ADMIN_PASSWORD}
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - 8080:443
    networks:
      - ft_transcendence_network
    volumes:
      - ft_transcendence_backend:/var/lib/postgresql/data
      - ./backend:/usr/src/
    depends_on:
      - ft_transcendence_database
      - ganache

networks:
  ft_transcendence_network:
    name: ft_transcendence_network

volumes:
  ganache-data:
    name: ft_transcendence_ganache-data
  ft_transcendence_database-data:
    name: ft_transcendence_database-data
  ft_transcendence_backend:
    name: ft_transcendence_backend
