# Generated by Django 3.2.10 on 2024-04-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aouth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
