# Generated by Django 3.2.25 on 2024-06-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draw',
            field=models.IntegerField(default=0),
        ),
    ]
