# Generated by Django 3.2.10 on 2024-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draw',
            field=models.IntegerField(default=0),
        ),
    ]
