# Generated by Django 3.2.25 on 2024-07-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.CharField(choices=[('pool', 'Pool'), ('semi_final', 'Semi Final'), ('final', 'Final'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
