# Generated by Django 3.2.10 on 2024-04-03 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('games', models.ManyToManyField(blank=True, related_name='games_tournament', to='games.Game')),
                ('players', models.ManyToManyField(related_name='players_tournament', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
