# Generated by Django 3.2.10 on 2024-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20240610_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='level',
            field=models.CharField(choices=[('pool', 'Pool'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('final', 'Final'), ('finished', 'Finished'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
