# Generated by Django 3.2.25 on 2024-07-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_level_up_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='level',
            field=models.CharField(choices=[('pool', 'Pool'), ('semi_final', 'Semi Final'), ('final', 'Final'), ('finished', 'Finished'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
