# Generated by Django 3.2.10 on 2024-04-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0002_user_match_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game'),
        ),
    ]
