# Generated by Django 3.2.10 on 2024-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240422_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_game',
        ),
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
