# Generated by Django 3.2.10 on 2024-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_validation_code_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validation_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
