# Generated by Django 3.2.10 on 2024-04-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_validation_code_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='user',
            name='twofactor_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
