# Generated by Django 3.2.10 on 2024-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_elo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='validation_code_expiration',
        ),
        migrations.AddField(
            model_name='user',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
