# Generated by Django 3.2.10 on 2024-06-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20240610_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='draw',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='validation_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='elo',
            field=models.IntegerField(default=0),
        ),
    ]
