# Generated by Django 3.2.25 on 2024-07-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_level'),
        ('users', '0024_auto_20240719_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_processed_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_processed_user', to='games.game'),
        ),
    ]
