# Generated by Django 3.2.25 on 2024-07-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20240719_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validation_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
