# Generated by Django 3.2.25 on 2024-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twofactor_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
