# Generated by Django 3.2.10 on 2024-04-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240422_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validation_code_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
