# Generated by Django 3.2.10 on 2024-04-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_validation_code_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='validation_code_created',
        ),
    ]
