# Generated by Django 3.2.10 on 2024-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validation_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
