# Generated by Django 3.2.25 on 2024-07-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_twofactor_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='twofactor_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
